name: FrickCheaters_CORE
version: 2021.1.1-pre
main: net.opensend.FrickCheaters_CORE.FrickCheaters_CORE
load: STARTUP
depend:
  - ProtocolLib
loadbefore:
  - FrickCheaters
commands:
  fccore:
    usage: "/fccore"